[package]
name = "stream_character"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
sqlx.workspace = true

subd-macros = { path = "../subd-macros/" }
