[package]
name = "obs_service"
version = "0.1.0"
edition = "2021"

[dependencies]

subd-types.workspace = true
sqlx.workspace = true
anyhow.workspace = true
obws.workspace = true
log.workspace = true
num-traits.workspace = true
serde.workspace = true
