[package]
name = "user_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subd-types = { path = "../subd-types/" }
subd-macros = { path = "../subd-macros/" }

anyhow.workspace = true
sqlx.workspace = true
